---
title: "Shiny tRophicPosition Report"
author: "Shiny tRophicPosition"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  word_document: default
  html_document: default
papersize: a4
params:
  data: NA
  include: NA
---

```{r setup, echo=FALSE}
library(knitr)
library(tinytex)
library(summarytools)
library(tRophicPosition)

knitr::opts_knit$set(root.dir = '../') 

st_options(
  plain.ascii = FALSE,
  style = "rmarkdown",
  dfSummary.style = "grid",
  dfSummary.varnumbers = FALSE,
  dfSummary.valid.col = FALSE,
  dfSummary.graph.magnif = .85,
  dfSummary.na.col = FALSE,
  headings = FALSE,
  footnote = NA,
  tmp.img.dir = ".",

  dfSummary.custom.2 =
    expression(paste(
      "Q1 & Q4 :",

      quantile(
        column_data,
        probs = .25,
        type = 2,
        names = FALSE,
        na.rm = TRUE
      ),
      digits = 1
      ,
      " & ",

      quantile(
        column_data,
        probs = 1,
        type = 2,
        names = FALSE,
        na.rm = TRUE
      ),
      digits = 1

    ))
)

data <- params$data
include <- params$include

```

---

```{r table, echo=FALSE, results = 'asis',message=FALSE,error=FALSE}
if ('DATA TABLE' %in% include) {
    tags$h2("DATA TABLE")
    kable(data, caption = "DATA TABLE")
}
```

---

```{r summary two, echo=FALSE, results ='asis',message=FALSE,error=FALSE}
if ('DATA SUMMARY' %in% include) {
  tags$h2("DATA SUMMARY") 
  kable(descr(data), caption = "DATA SUMMARY")
}
```

---

```{r summary one, echo=FALSE, results  = 'asis',message=FALSE,error=FALSE}
if ('DATA SUMMARY' %in% include) {
  define_keywords(title.dfSummary = "DATA SUMMARY")
  
  dfSummary(
    data,
    plain.ascii = FALSE,
    style = "grid",
    tmp.img.dir = ".",
    method = "render"
  )
}
```

---

```{r species, echo=FALSE, results  = 'asis',message=FALSE,warning = FALSE,error=FALSE}
if ('DATA SPECIES' %in% include) {
  tags$h2("DATA SPECIES")
   tRophicPosition::screenFoodWeb(
      df = data,
      grouping = c("Spp", "FG"),
      printSummary = FALSE,
      title = "DATA SPECIES",
      order = TRUE, 
      caption = "DATA SPECIES"
    )
}
```